project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Predicting Asthma Prevalence by Census Tracts in Philadelphia, PA"
  site-url: "https://musa-550-fall-2023.github.io/Final-Python-MC-AFA" 
  repo-url: https://github.com/MUSA-550-Fall-2023/Final-Python-MC-AFA
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Nick Hand, 2023"

  sidebar:
    logo: "images/asthma.jpg"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Introduction
      - section: Our Model/About1.qmd
        contents:
          - Our Model/1-Exploratory-Analysis.ipynb 
          - Our Model/2-Regression-Analysis.ipynb
          - Our Model/3-Predictions.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true